site_name: Jorn & Wouter
pages:
  - Home: index.md
#  - Software Requirement Specification: SRS_v1-0-3.md
  - SRS: SRS_v1-0-4.md
#  - Software Design Description: SDD_v1-0-1.md
  - SDD: SDD_v1-0-1.md
#  - Vision: Vision_v1-0-1.md
#  - Suplementary-Specification: Supplementary_Specification-v1-0-5.md
#  - Glossary: Glossary_v1-0-1.md
#  - FDUC: FDUC_v1-0-6.md
#  - Tasks: Tasks_v1-0-4.md
#  - CSD: CSD_uc1-reserverAuto.md
theme: readthedocs
repo_url: https://github.com/jornbrouwer/RentIT/master/
